### ISSUE TITLE
Increment of the size of bytes storage

### ISSUE THREAD

**Issue by kuabhish** [bmuller/rpcudp#15]
I was trying to store a frame of video in a kademlia node. the frame size is (720,1280,3). Which clearly is over the limit of 8192 in this : 
https://github.com/bmuller/rpcudp/blob/ec56638ce963a4ea49bc34ac407ec7c09bae816f/rpcudp/protocol.py#L122

So, How should I handle this situation? Some suggesstions will be helpful. Thanks

**Comment by bmuller** [comment]
This limit exists to ensure requests don't exceed the typical frame size in UDP.  

If you're using this in Kademlia - To store anything larger you'll just need to split the data and use something like a [Merkle Tree](https://en.wikipedia.org/wiki/Merkle_tree) to keep track of all the parts.

**Comment by kuabhish** [comment]
If I have a video of let's say 300 frames and each frame of size  (720,1280,3). 
So, Are you suggesting to create 300 nodes and store each frame into Merklee tree or create only one node and store the whole video in a single Markle Tree?

How should I start implementing this?

**Comment by bmuller** [comment]
@kuabhish I'm not sure why you're coming to me to design your project for you.  I don't know you, I don't know anything about your project, and it's totally unrelated to this repo or any of my other projects.  You've sent me multiple harassing emails to my personal account, and my next step is blocking you from all my projects and reporting you to Github.  Please stop sending me messages asking me to help you with your project.
