### ISSUE TITLE
Python 3.11: AttributeError: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by hiway** [bmuller/rpcudp#21]
```
/site-packages/rpcudp/protocol.py:71> exception=AttributeError("module 'asyncio' has no attribute 'coroutine'")>
Traceback (most recent call last):
File "[...]lib/python3.11/site-packages/rpcudp/protocol.py", line 83, in _accept_request
func = asyncio.coroutine(func)
^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

> Support for generator-based coroutines is deprecated and is removed in Python 3.11.
( https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines )

As explored in the pull-request #20 , 
one could wrap the plain function in a coroutine
or call the function directly, without `await`.

Refer: https://github.com/bmuller/rpcudp/pull/20#discussion_r1161135572

```
if not asyncio.iscoroutinefunction(func):
    response = func(address, *args)
else:
    response = await func(address, *args)
```

**Comment by IsuruLakshan170** [comment]
its working

**Comment by cmpunches** [comment]
Can this be added into the release that's in PIP?  This not being here causes unworkable problems with kademlia.  

In the meantime I just hotfixed rpcudp/protocol.py in a venv with this and it did fix it.

**Comment by bmuller** [comment]
[Version 5.0.0](https://pypi.org/project/rpcudp/) includes this fix.  🙏
