### ISSUE TITLE
Remove unnecessary 20 byte message overhead.

### ISSUE THREAD

**Issue by F483** [bmuller/rpcudp#4]
Currently every packet [includes a 20 byte message id overhead](https://github.com/bmuller/rpcudp/blob/master/rpcudp/protocol.py#L32) which is costly in terms of reliability. It could be entirely removed if the hash of the packet were used as the message id.

This does burden the user to ensure each packet contains enough entropy, as to avoid a collision. But this can be done by the user with a much smaller nonce, if the data is expected to not contain enough entropy.

To maintain some level of backwards compatibility [additional datagram prefixes](https://github.com/bmuller/rpcudp/blob/master/rpcudp/protocol.py#L35) could be used, `b'\x02'` `b'\x03'`. Though it is probably with breaking compatibility altogether.

PS: I plan eventually adding end to end encryption to rpcudp, or forking if it makes more sense. Since this would break compatibility. I'm adding additional issues that also would require a break. This should keep everyone on the same page as to a possible future direction.

**Comment by bmuller** [comment]
When a response is received by a caller, the caller MUST be guaranteed that it is the response expected for the given call.  Making the same call multiple times would remove this guarantee.  Unless there is some other way to make this guarantee, we've got to keep the message id (and I don't consider placing the burden on the user of the lib to add a nonce to be an acceptable burden).

**Comment by F483** [comment]
Even if it is a non default option that the user must explicitly enable?

**Comment by bmuller** [comment]
It seems dangerous for a gain of just 20 bytes.  It seems like peculiar functionality that applications wouldn't (or shouldn't) be OK with.  If you strongly believe those 20 bytes are _really_ worth it for you, though - then I'd be willing to consider a PR.

**Comment by F483** [comment]
[Generally 512 byte is considered to be a safe packet size](http://stackoverflow.com/questions/1098897/what-is-the-largest-safe-udp-packet-size-on-the-internet) and anything above would reduce reliability. That makes about a 4% overhead for a safe packet, which I consider to be significant. This becomes even more pressing if authentication were to be added (a secp256k1 signature is 65 bytes). And adding encryption would likely also have a cost.

If encryption is added properly packets would also look like random noise and make hashing reliable as a message id.
