### ISSUE TITLE
Add authentication and end to end encryption.

### ISSUE THREAD

**Issue by F483** [bmuller/rpcudp#6]
Currently packets are blindly trusted, leaving authentication up to the user and the same for encryption. In a post Snowden world this is no longer acceptable.

Good options for encryption and authentication now exist for memory constrained protocols, as shown by bitcoin. Which authentication/encryption schema to use is however subject to much debate.

PS: Since this would break compatibility, I'm also adding additional issues that also would require a break. This should keep everyone on the same page as to a possible future direction.

**Comment by bmuller** [comment]
Authentication and encryption are the responsibility of the client, not the underlying transport mechanism.

**Comment by F483** [comment]
But if its not on the transport mechanism, direction/ids/rpc-calls are exposed to tracking and thus reveal vital critical meta data.

> “We Kill People Based on Metadata,” - Former CIA/NSA Boss

**Comment by bmuller** [comment]
What's an example of "vital critical meta data" that would be exposed?

**Comment by F483** [comment]
The rpc function name alone would be enough. It would offer conclusive documentation of all users interactions, regardless if the arguments are encrypted or not.

Snowden for example would not use this as the form of any interactions with other parties would be exposed. In this day and age is is not acceptable that any data be transferred in the clear, all data should look like noise.

**Comment by bmuller** [comment]
The RPC function name and parameters are up to the user (and can therefore be encrypted by them).

**Comment by F483** [comment]
The parameters yes, but using random function names is not practical since they are required as method names. It could be done via introspection, but its hardly an elegant solution as it would basally just be hacking rpcupd to the point where you would be better off making a fork to support encryption.

I think it generally makes sense to add encryption/authentication at the lowest possible layer for the following reasons.
- It can be done correctly once and not require each user to add it individually, which increases the chance of a vulnerable implementation.
- It reduces the amount of meta data exposed to the minimum (entire datagram can be encrypted).

**Comment by bmuller** [comment]
I'm not suggesting random function names - but rather encrypted ones.  I'm also not saying encryption isn't good/necessary - just that this lib isn't the place to do it.  The way I see it, there are two decent options for where to do it:
1. Encryption could be done by the user (encrypting function name, arguments)
2. Encryption could be done in some sort of wrapper (in the same way that HTTP is made secure by wrapping it in TLS).

Either way, I don't think encryption is the concern of a library that is solely concerned with providing a method for RPC over UDP.  I think the best course for you would be the second option that can then be used to wrap UDP messages created in this lib, in the same way that SSL/TLS secure the protocols that they wrap for TCP.

**Comment by F483** [comment]
I agree that your 2. point is the better, provided that there is a simple good way to wrap rpcudp packets.

My knowledge of twisted is not to good, is there a general way in twisted where I could insert an encryption layer below rpcudp to do this?

**Comment by bmuller** [comment]
I have no idea how this is typically done for something stateless like UDP - but here's how you can wrap a protocol in TLS - https://twistedmatrix.com/documents/14.0.0/core/howto/ssl.html
